### ISSUE TITLE
"Test Endpoint" button only visible on-hover

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-provider-manager#2]
When editing the endpoint, the "Test Endpoint" button isn't visible until hovering over it.

![](http://g.recordit.co/RY0jBLLd8x.gif)

**Comment by Tolmark12** [comment]
Fixed ready for deploy `bower update providers`

**Comment by jedgalbraith** [comment]
Looks good. Thanks.
